#!/bin/bash

echo "⚡ Quick Setup for Dynatrace BizObs Generator"
echo "============================================="
echo ""
echo "1. Configure your Dynatrace environment:"
echo "   selectEnvironment"
echo ""
echo "2. Start the application:"
echo "   npm start"
echo ""
echo "3. Open in browser:"
echo "   http://localhost:8080"
echo ""
echo "4. For MCP Server integration:"
echo "   - Install Dynatrace MCP extension in VS Code"
echo "   - Configure with your DT_ENVIRONMENT"
echo ""
echo "📚 Documentation: https://dynatrace-wwse.github.io/codespaces-framework/"
